/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package feedback;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;

/**
 *
 * @author owner
 */
public class AdminLogin extends javax.swing.JFrame {

    /**
     * Creates new form AdminLogin
     */
    public AdminLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WrongPasswordDialog = new javax.swing.JDialog();
        WrongPasswordOKButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        AdminPage = new javax.swing.JDialog();
        InsertTeacherButton = new javax.swing.JButton();
        RemoveTeacherButton = new javax.swing.JButton();
        ScoreRequestButton = new javax.swing.JButton();
        LogOutButton = new javax.swing.JButton();
        InsertTeacherDialog = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TeacherCreationButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        SemComboBox = new javax.swing.JComboBox();
        SecComboBox = new javax.swing.JComboBox();
        SubComboBox = new javax.swing.JComboBox();
        FName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Fno = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TitleField = new javax.swing.JTextField();
        p1ComboBox = new javax.swing.JComboBox();
        p2ComboBox = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        DoneDialog = new javax.swing.JDialog();
        DoneOKButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        RemoveTeacherDialog = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        RemoveIDCombo = new javax.swing.JComboBox();
        RemoveButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        ChangePassword = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        NewPasswordField = new javax.swing.JPasswordField();
        ChangePasswordButton = new javax.swing.JButton();
        ReportWindow = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        StudentScoreValueLabel = new javax.swing.JLabel();
        PeerScoreValueLabel = new javax.swing.JLabel();
        DoneButton = new javax.swing.JButton();
        NameLabel = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        NotGivenList = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        stu1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();

        WrongPasswordOKButton.setText("OK");
        WrongPasswordOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WrongPasswordOKButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Wrong Password!");

        javax.swing.GroupLayout WrongPasswordDialogLayout = new javax.swing.GroupLayout(WrongPasswordDialog.getContentPane());
        WrongPasswordDialog.getContentPane().setLayout(WrongPasswordDialogLayout);
        WrongPasswordDialogLayout.setHorizontalGroup(
            WrongPasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WrongPasswordDialogLayout.createSequentialGroup()
                .addGroup(WrongPasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WrongPasswordDialogLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel4))
                    .addGroup(WrongPasswordDialogLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(WrongPasswordOKButton)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        WrongPasswordDialogLayout.setVerticalGroup(
            WrongPasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WrongPasswordDialogLayout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(WrongPasswordOKButton)
                .addGap(103, 103, 103))
        );

        AdminPage.setMinimumSize(new java.awt.Dimension(450, 344));

        InsertTeacherButton.setText("Insert Teacher");
        InsertTeacherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertTeacherButtonActionPerformed(evt);
            }
        });

        RemoveTeacherButton.setText("Remove Teacher");
        RemoveTeacherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveTeacherButtonActionPerformed(evt);
            }
        });

        ScoreRequestButton.setText("Generate Teacher Feedback Report");
        ScoreRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScoreRequestButtonActionPerformed(evt);
            }
        });

        LogOutButton.setText("Logout");
        LogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AdminPageLayout = new javax.swing.GroupLayout(AdminPage.getContentPane());
        AdminPage.getContentPane().setLayout(AdminPageLayout);
        AdminPageLayout.setHorizontalGroup(
            AdminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPageLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(AdminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ScoreRequestButton, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(RemoveTeacherButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InsertTeacherButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LogOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        AdminPageLayout.setVerticalGroup(
            AdminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPageLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(InsertTeacherButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RemoveTeacherButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ScoreRequestButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LogOutButton)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        InsertTeacherDialog.setMinimumSize(new java.awt.Dimension(595, 482));

        jLabel5.setText("Faculty Name : ");

        jLabel6.setText("Semester Handled : ");

        jLabel7.setText("Section Handled : ");

        jLabel8.setText("Subject handled :");

        TeacherCreationButton.setText("Add Teacher");
        TeacherCreationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeacherCreationButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Faculty Number : ");

        jLabel10.setText("Faculty Title : ");

        p1ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        p2ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel12.setText("Select Peer 1 id : ");

        jLabel13.setText("Select Peer 2 id :");

        javax.swing.GroupLayout InsertTeacherDialogLayout = new javax.swing.GroupLayout(InsertTeacherDialog.getContentPane());
        InsertTeacherDialog.getContentPane().setLayout(InsertTeacherDialogLayout);
        InsertTeacherDialogLayout.setHorizontalGroup(
            InsertTeacherDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertTeacherDialogLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(InsertTeacherDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InsertTeacherDialogLayout.createSequentialGroup()
                        .addComponent(TeacherCreationButton)
                        .addGap(86, 86, 86)
                        .addComponent(jButton1))
                    .addGroup(InsertTeacherDialogLayout.createSequentialGroup()
                        .addGroup(InsertTeacherDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(InsertTeacherDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(InsertTeacherDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(SubComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SecComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SemComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(FName)
                                .addComponent(Fno, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TitleField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(p2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        InsertTeacherDialogLayout.setVerticalGroup(
            InsertTeacherDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertTeacherDialogLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(InsertTeacherDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InsertTeacherDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TitleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InsertTeacherDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(FName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InsertTeacherDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InsertTeacherDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(InsertTeacherDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(SemComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InsertTeacherDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(SecComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InsertTeacherDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(SubComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(InsertTeacherDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TeacherCreationButton)
                    .addComponent(jButton1))
                .addGap(35, 35, 35))
        );

        DoneDialog.setMinimumSize(new java.awt.Dimension(475, 384));

        DoneOKButton.setText("OK");
        DoneOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneOKButtonActionPerformed(evt);
            }
        });

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Done!!");

        javax.swing.GroupLayout DoneDialogLayout = new javax.swing.GroupLayout(DoneDialog.getContentPane());
        DoneDialog.getContentPane().setLayout(DoneDialogLayout);
        DoneDialogLayout.setHorizontalGroup(
            DoneDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoneDialogLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(DoneDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DoneOKButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        DoneDialogLayout.setVerticalGroup(
            DoneDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DoneDialogLayout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(28, 28, 28)
                .addComponent(DoneOKButton)
                .addGap(114, 114, 114))
        );

        RemoveTeacherDialog.setMinimumSize(new java.awt.Dimension(400, 309));

        jLabel14.setText("Select faculty ID to be removed :");

        RemoveIDCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        RemoveButton.setText("Remove");
        RemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RemoveTeacherDialogLayout = new javax.swing.GroupLayout(RemoveTeacherDialog.getContentPane());
        RemoveTeacherDialog.getContentPane().setLayout(RemoveTeacherDialogLayout);
        RemoveTeacherDialogLayout.setHorizontalGroup(
            RemoveTeacherDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RemoveTeacherDialogLayout.createSequentialGroup()
                .addGroup(RemoveTeacherDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RemoveTeacherDialogLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel14)
                        .addGap(45, 45, 45)
                        .addComponent(RemoveIDCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RemoveTeacherDialogLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(RemoveButton)
                        .addGap(56, 56, 56)
                        .addComponent(CancelButton)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        RemoveTeacherDialogLayout.setVerticalGroup(
            RemoveTeacherDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RemoveTeacherDialogLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(RemoveTeacherDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(RemoveIDCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(RemoveTeacherDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RemoveButton)
                    .addComponent(CancelButton))
                .addGap(70, 70, 70))
        );

        jLabel15.setText("New Password : ");

        ChangePasswordButton.setText("OK");
        ChangePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePasswordButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ChangePasswordLayout = new javax.swing.GroupLayout(ChangePassword.getContentPane());
        ChangePassword.getContentPane().setLayout(ChangePasswordLayout);
        ChangePasswordLayout.setHorizontalGroup(
            ChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChangePasswordLayout.createSequentialGroup()
                .addGroup(ChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ChangePasswordLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel15)
                        .addGap(34, 34, 34)
                        .addComponent(NewPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ChangePasswordLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(ChangePasswordButton)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        ChangePasswordLayout.setVerticalGroup(
            ChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChangePasswordLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(ChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(NewPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(ChangePasswordButton)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        ReportWindow.setMinimumSize(new java.awt.Dimension(407, 360));

        jLabel16.setText("Select Faculty No : ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        StudentScoreValueLabel.setText("Student Score Value");

        PeerScoreValueLabel.setText("Peer Score Value");

        DoneButton.setText("Done");
        DoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneButtonActionPerformed(evt);
            }
        });

        NameLabel.setText("jLabel18");

        jButton4.setText("Display");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ReportWindowLayout = new javax.swing.GroupLayout(ReportWindow.getContentPane());
        ReportWindow.getContentPane().setLayout(ReportWindowLayout);
        ReportWindowLayout.setHorizontalGroup(
            ReportWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportWindowLayout.createSequentialGroup()
                .addGroup(ReportWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReportWindowLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(ReportWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(StudentScoreValueLabel)
                            .addGroup(ReportWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(NameLabel)
                                .addComponent(jLabel16)))
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReportWindowLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)))
                .addGroup(ReportWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DoneButton)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PeerScoreValueLabel))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        ReportWindowLayout.setVerticalGroup(
            ReportWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportWindowLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(ReportWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NameLabel)
                .addGap(32, 32, 32)
                .addGroup(ReportWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StudentScoreValueLabel)
                    .addComponent(PeerScoreValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(ReportWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DoneButton)
                    .addComponent(jButton4))
                .addGap(41, 41, 41))
        );

        jLabel17.setText("These students haven't given the feedback : ");

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NotGivenListLayout = new javax.swing.GroupLayout(NotGivenList.getContentPane());
        NotGivenList.getContentPane().setLayout(NotGivenListLayout);
        NotGivenListLayout.setHorizontalGroup(
            NotGivenListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NotGivenListLayout.createSequentialGroup()
                .addGroup(NotGivenListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NotGivenListLayout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jButton2))
                    .addGroup(NotGivenListLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(NotGivenListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stu1)
                            .addComponent(jLabel17))))
                .addContainerGap(468, Short.MAX_VALUE))
        );
        NotGivenListLayout.setVerticalGroup(
            NotGivenListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NotGivenListLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel17)
                .addGap(39, 39, 39)
                .addComponent(stu1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 400, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(55, 55, 55))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feedback/sandtiger_logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Welcome to BMSCE Feedback System!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 11, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Password : ");

        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(LoginButton)
                        .addGap(69, 69, 69)
                        .addComponent(ExitButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginButton)
                    .addComponent(ExitButton))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
        if(!(PasswordField.getText().equals(pass)))
        {
            WrongPasswordDialog.setLocationRelativeTo(null);
            WrongPasswordDialog.setIconImage(new ImageIcon(getClass().getResource("win_logo.png")).getImage());
            WrongPasswordDialog.setTitle("Wrong Password!");
            WrongPasswordDialog.setVisible(true);
        }
        else
        {
            AdminPage.setVisible(true);
        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void WrongPasswordOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WrongPasswordOKButtonActionPerformed
        // TODO add your handling code here:
        WrongPasswordDialog.setVisible(false);
    }//GEN-LAST:event_WrongPasswordOKButtonActionPerformed

    private void RemoveTeacherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveTeacherButtonActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("java.sql.Driver");
            Connection  con = DriverManager.getConnection("jdbc:mysql://localhost/feedback","root","jirs");
            System.out.println("Connecting JDBC...(main)");
            System.out.println("Connection Sucessful!!");
            Statement stmt = con.createStatement();
            RemoveIDCombo.removeAllItems();;
            String q ="select fno from faculty order BY fno;";
            ResultSet rs = stmt.executeQuery(q);
            while(rs.next())
            {
                String id = rs.getString("fno");
                RemoveIDCombo.addItem(id);
            }
            RemoveTeacherDialog.setVisible(true);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }

    }//GEN-LAST:event_RemoveTeacherButtonActionPerformed

    private void InsertTeacherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertTeacherButtonActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("java.sql.Driver");
            Connection  con = DriverManager.getConnection("jdbc:mysql://localhost/feedback","root","jirs");
            System.out.println("Connecting JDBC...(main)");
            System.out.println("Connection Sucessful!!");
            Statement stmt = con.createStatement();
            String q ="select * from `section`;";
            ResultSet rs = stmt.executeQuery(q);
            SecComboBox.removeAllItems();
            SemComboBox.removeAllItems();
            SubComboBox.removeAllItems();
            p1ComboBox.removeAllItems();
            p2ComboBox.removeAllItems();
            while(rs.next())
            {
                String sem = rs.getString("sem_no");
                SemComboBox.addItem(sem);
                String sec = rs.getString("sec");
                SecComboBox.addItem(sec);                
            }
            q = "select subcode from subject;";
            rs = stmt.executeQuery(q);
            while(rs.next())
            {
                String sub = rs.getString("subcode");
                SubComboBox.addItem(sub);
            }
            q = "select fno from faculty order by fno;";
            rs = stmt.executeQuery(q);
            while(rs.next())
            {
                String p1 = rs.getString("fno");
                p1ComboBox.addItem(p1);
                String p2 = rs.getString("fno");
                p2ComboBox.addItem(p2);
            }
            InsertTeacherDialog.setVisible(true);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }

    }//GEN-LAST:event_InsertTeacherButtonActionPerformed

    private void TeacherCreationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeacherCreationButtonActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("java.sql.Driver");
            Connection  con = DriverManager.getConnection("jdbc:mysql://localhost/feedback","root","jirs");
            System.out.println("Connecting JDBC...(main)");
            System.out.println("Connection Sucessful!!");
            Statement stmt = con.createStatement();
            String name = FName.getText();
            String no = Fno.getText();
            String tit = TitleField.getText();
            String sem = (String) SemComboBox.getSelectedItem();
            String sec = (String) SecComboBox.getSelectedItem();
            String sub = (String) SubComboBox.getSelectedItem();
            String p1 = (String) p1ComboBox.getSelectedItem();
            String p2 = (String) p2ComboBox.getSelectedItem();
            String q = "INSERT INTO feedback.faculty (fno, fname, peer1, peer2, subcode, sem1, sec1, sem2, sec2, password, `Title`) VALUES ("+no+", '"+name+"', "+p1+", "+p2+", '"+sub+"', "+sem+", '"+sec+"', NULL, NULL, '"+no+"', '"+tit+"');";
            String q1 = "INSERT INTO feedback.teaches (tyear, fno, subcode, sf1, sf2, sf3, pf1, pf2, comments) VALUES (2013,"+no+" , '"+sub+"', 0.0, 0.0, 0.0, 0.0, 0.0, NULL);";
            stmt.executeUpdate(q);
            stmt.executeUpdate(q1);
            DoneDialog.setVisible(true);
            InsertTeacherDialog.setVisible(false);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }

    }//GEN-LAST:event_TeacherCreationButtonActionPerformed

    private void DoneOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneOKButtonActionPerformed
        // TODO add your handling code here:
        DoneDialog.setVisible(false);
    }//GEN-LAST:event_DoneOKButtonActionPerformed

    private void LogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_LogOutButtonActionPerformed

    private void RemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveButtonActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("java.sql.Driver");
            Connection  con = DriverManager.getConnection("jdbc:mysql://localhost/feedback","root","jirs");
            System.out.println("Connecting JDBC...(main)");
            System.out.println("Connection Sucessful!!");
            Statement stmt = con.createStatement();
            String did = (String) RemoveIDCombo.getSelectedItem();
            String q ="Delete FROM teaches WHERE fno='"+did+"';";
            String q1 = "DELETE FROM faculty where fno='"+did+"';";
            stmt.executeUpdate(q);
            stmt.executeUpdate(q1);
            DoneDialog.setVisible(true);
            RemoveTeacherDialog.setVisible(false);
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }

    }//GEN-LAST:event_RemoveButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        RemoveTeacherDialog.setVisible(false);
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void ChangePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePasswordButtonActionPerformed
        // TODO add your handling code here:
        pass = PasswordField.getText();
        DoneDialog.setVisible(true);
        ChangePassword.setVisible(false);
    }//GEN-LAST:event_ChangePasswordButtonActionPerformed

    private void ScoreRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScoreRequestButtonActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("java.sql.Driver");
            Connection  con = DriverManager.getConnection("jdbc:mysql://localhost/feedback","root","jirs");
            System.out.println("Connecting JDBC...(main)");
            System.out.println("Connection Sucessful!!");
            Statement stmt = con.createStatement();
            String q = "SELECT count(*) FROM student;";
            ResultSet rs = stmt.executeQuery(q);
            int totstu = 0,givstu = 0;
            if(rs.next())
            {
                totstu = rs.getInt(1);
            }
            q = "SELECT sum(`Y_N`) FROM student;";
            rs = stmt.executeQuery(q);
            if(rs.next())
            {
                givstu = rs.getInt(1);
            }
            q = "SELECT fno FROM faculty ORDER BY fno;";
            rs = stmt.executeQuery(q);
            jComboBox1.removeAllItems();
            while(rs.next())
            {
                String temp = rs.getString(1);
                jComboBox1.addItem(temp);
            }
            if(totstu!=givstu)
            {
                q = "SELECT Name FROM student where `Y_N` = 0;";
                rs = stmt.executeQuery(q);                
                String s2 = " ";
                String s3;
                while(rs.next())
                {
                    s3 = rs.getString("Name");
                    s2=s2.concat(" ");
                    s2=s2.concat(s3);
                }
                System.out.println(s2);
                stu1.setText(s2);
                NotGivenList.setVisible(true);
            }
            else
            {
                StudentScoreValueLabel.setVisible(false);
                PeerScoreValueLabel.setVisible(false);
                NameLabel.setVisible(false);
                
                ReportWindow.setVisible(true);
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }

    }//GEN-LAST:event_ScoreRequestButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        NotGivenList.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void DoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneButtonActionPerformed
        // TODO add your handling code here:
        ReportWindow.setVisible(false);
    }//GEN-LAST:event_DoneButtonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
         Class.forName("java.sql.Driver");
         Connection  con = DriverManager.getConnection("jdbc:mysql://localhost/feedback","root","jirs");
            System.out.println("Connecting JDBC...(main)");
            System.out.println("Connection Sucessful!!");
            Statement stmt = con.createStatement();
            String fidsel = (String) jComboBox1.getSelectedItem();
            String q = "SELECT count(*) FROM student;";
            ResultSet rs = stmt.executeQuery(q);
            int totstu = 0,givstu = 0;
            if(rs.next())
            {
                totstu = rs.getInt(1);
            }
                q = "SELECT fname FROM faculty where fno="+fidsel+";";
                rs = stmt.executeQuery(q);
                if(rs.next())
                {
                    NameLabel.setText("Name : "+rs.getString(1));
                    NameLabel.setVisible(true);
                }
                q = "select sf1/"+totstu+" from teaches where fno="+fidsel+";";
                rs = stmt.executeQuery(q);   
                if(rs.next())
                {
                    StudentScoreValueLabel.setText(rs.getString(1));
                    StudentScoreValueLabel.setVisible(true);
                }
                q = "select pf1/2 from teaches where fno="+fidsel+";";
                rs = stmt.executeQuery(q);   
                if(rs.next())
                {
                    PeerScoreValueLabel.setText(rs.getString(1));
                    PeerScoreValueLabel.setVisible(true);
                }
            
         
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        InsertTeacherDialog.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogin().setVisible(true);
            }
        });
    }
    private String pass = "bmsadmin";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog AdminPage;
    private javax.swing.JButton CancelButton;
    private javax.swing.JDialog ChangePassword;
    private javax.swing.JButton ChangePasswordButton;
    private javax.swing.JButton DoneButton;
    private javax.swing.JDialog DoneDialog;
    private javax.swing.JButton DoneOKButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JTextField FName;
    private javax.swing.JTextField Fno;
    private javax.swing.JButton InsertTeacherButton;
    private javax.swing.JDialog InsertTeacherDialog;
    private javax.swing.JButton LogOutButton;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JPasswordField NewPasswordField;
    private javax.swing.JDialog NotGivenList;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PeerScoreValueLabel;
    private javax.swing.JButton RemoveButton;
    private javax.swing.JComboBox RemoveIDCombo;
    private javax.swing.JButton RemoveTeacherButton;
    private javax.swing.JDialog RemoveTeacherDialog;
    private javax.swing.JDialog ReportWindow;
    private javax.swing.JButton ScoreRequestButton;
    private javax.swing.JComboBox SecComboBox;
    private javax.swing.JComboBox SemComboBox;
    private javax.swing.JLabel StudentScoreValueLabel;
    private javax.swing.JComboBox SubComboBox;
    private javax.swing.JButton TeacherCreationButton;
    private javax.swing.JTextField TitleField;
    private javax.swing.JDialog WrongPasswordDialog;
    private javax.swing.JButton WrongPasswordOKButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox p1ComboBox;
    private javax.swing.JComboBox p2ComboBox;
    private javax.swing.JLabel stu1;
    // End of variables declaration//GEN-END:variables
}
