/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package feedback;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;

/**
 *
 * @author owner
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setTitle("BMSCE Feedback System");
        this.setIconImage(new ImageIcon(getClass().getResource("win_logo.png")).getImage());
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ErrorPane = new javax.swing.JOptionPane();
        StudentHome = new javax.swing.JDialog();
        FullName = new javax.swing.JLabel();
        Sem = new javax.swing.JLabel();
        Section = new javax.swing.JLabel();
        USN = new javax.swing.JLabel();
        GiveFeedbackButton = new javax.swing.JButton();
        LogOutButton = new javax.swing.JButton();
        Gender = new javax.swing.JLabel();
        ChangePasswordButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        WelcomeLabel = new javax.swing.JLabel();
        TeacherHome = new javax.swing.JDialog();
        FullNameTeacher = new javax.swing.JLabel();
        SectionCoveredLabel = new javax.swing.JLabel();
        ChangeUserNameButton = new javax.swing.JButton();
        TeacherChangePasswordButton = new javax.swing.JButton();
        TeacherLogOutButton = new javax.swing.JButton();
        TeacherGiveFeedback = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        WelcomeLabelTeacher = new javax.swing.JLabel();
        DoneDialog = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        DoneButton = new javax.swing.JButton();
        ChangePasswordDialog = new javax.swing.JDialog();
        TypeNewPasswordLabel = new javax.swing.JLabel();
        ConfirmChangePassword = new javax.swing.JButton();
        CancelChangePassword = new javax.swing.JButton();
        ChangePasswordField = new javax.swing.JPasswordField();
        StudentFeedbackDialog = new javax.swing.JDialog();
        TeacherSelection = new javax.swing.JComboBox();
        ProceedStudent = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Subject = new javax.swing.JDialog();
        SubmitStuFeedback = new javax.swing.JButton();
        q1 = new javax.swing.JComboBox();
        q2 = new javax.swing.JComboBox();
        q3 = new javax.swing.JComboBox();
        q4 = new javax.swing.JComboBox();
        q5 = new javax.swing.JComboBox();
        q6 = new javax.swing.JComboBox();
        q7 = new javax.swing.JComboBox();
        q8 = new javax.swing.JComboBox();
        q9 = new javax.swing.JComboBox();
        q10 = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        TeachSub = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        TeachName = new javax.swing.JLabel();
        StuFeedbackDone = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        StuSubError = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        FeedbackErrorOKButton = new javax.swing.JButton();
        FeedbackDone = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        UserField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();
        Exitbutton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        ErrorPane.setMessageType(2);

        StudentHome.setTitle("Welcome!");
        StudentHome.setAlwaysOnTop(true);
        StudentHome.setMinimumSize(new java.awt.Dimension(500, 500));

        FullName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FullName.setText("Name");

        Sem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Sem.setText("Sem");

        Section.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Section.setText("Sec");

        USN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        USN.setText("USN");

        GiveFeedbackButton.setText("Give Feedback");
        GiveFeedbackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GiveFeedbackButtonActionPerformed(evt);
            }
        });

        LogOutButton.setText("Log Out");
        LogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutButtonActionPerformed(evt);
            }
        });

        Gender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Gender.setText("Gender");

        ChangePasswordButton.setText("Change Password");
        ChangePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePasswordButtonActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 102, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        WelcomeLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        WelcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        WelcomeLabel.setText("Welcome");
        WelcomeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        WelcomeLabel.setMaximumSize(new java.awt.Dimension(0, 0));
        WelcomeLabel.setMinimumSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WelcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(WelcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout StudentHomeLayout = new javax.swing.GroupLayout(StudentHome.getContentPane());
        StudentHome.getContentPane().setLayout(StudentHomeLayout);
        StudentHomeLayout.setHorizontalGroup(
            StudentHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentHomeLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(StudentHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentHomeLayout.createSequentialGroup()
                        .addGroup(StudentHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Section, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Sem, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FullName, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(USN, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                    .addComponent(Gender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(StudentHomeLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(GiveFeedbackButton)
                .addGap(80, 80, 80)
                .addComponent(ChangePasswordButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogOutButton)
                .addGap(86, 86, 86))
        );
        StudentHomeLayout.setVerticalGroup(
            StudentHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentHomeLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(FullName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sem, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Section, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(USN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(StudentHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GiveFeedbackButton)
                    .addComponent(ChangePasswordButton)
                    .addComponent(LogOutButton))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        TeacherHome.setTitle("Welcome!");
        TeacherHome.setMinimumSize(new java.awt.Dimension(500, 250));

        FullNameTeacher.setText("Name");

        SectionCoveredLabel.setText("Section Covered");

        ChangeUserNameButton.setText("Change User Name");
        ChangeUserNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeUserNameButtonActionPerformed(evt);
            }
        });

        TeacherChangePasswordButton.setText("Change Password");

        TeacherLogOutButton.setText("Log Out");
        TeacherLogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeacherLogOutButtonActionPerformed(evt);
            }
        });

        TeacherGiveFeedback.setText("Give Feedback");

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        WelcomeLabelTeacher.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        WelcomeLabelTeacher.setForeground(new java.awt.Color(255, 255, 255));
        WelcomeLabelTeacher.setText("Welcome");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WelcomeLabelTeacher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(WelcomeLabelTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout TeacherHomeLayout = new javax.swing.GroupLayout(TeacherHome.getContentPane());
        TeacherHome.getContentPane().setLayout(TeacherHomeLayout);
        TeacherHomeLayout.setHorizontalGroup(
            TeacherHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(TeacherHomeLayout.createSequentialGroup()
                .addGroup(TeacherHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TeacherHomeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(FullNameTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TeacherHomeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SectionCoveredLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TeacherHomeLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(TeacherGiveFeedback))
                    .addGroup(TeacherHomeLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(ChangeUserNameButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TeacherChangePasswordButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TeacherLogOutButton)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        TeacherHomeLayout.setVerticalGroup(
            TeacherHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeacherHomeLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FullNameTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SectionCoveredLabel)
                .addGap(42, 42, 42)
                .addComponent(TeacherGiveFeedback)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TeacherHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChangeUserNameButton)
                    .addComponent(TeacherChangePasswordButton)
                    .addComponent(TeacherLogOutButton))
                .addGap(97, 97, 97))
        );

        DoneDialog.setAlwaysOnTop(true);
        DoneDialog.setMinimumSize(new java.awt.Dimension(400, 300));

        jLabel5.setText("Done!!");

        DoneButton.setText("OK");
        DoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DoneDialogLayout = new javax.swing.GroupLayout(DoneDialog.getContentPane());
        DoneDialog.getContentPane().setLayout(DoneDialogLayout);
        DoneDialogLayout.setHorizontalGroup(
            DoneDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoneDialogLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(DoneDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DoneButton)
                    .addComponent(jLabel5))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        DoneDialogLayout.setVerticalGroup(
            DoneDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoneDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DoneButton)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        ChangePasswordDialog.setMinimumSize(new java.awt.Dimension(500, 300));

        TypeNewPasswordLabel.setText("Type new password : ");

        ConfirmChangePassword.setText("OK");
        ConfirmChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmChangePasswordActionPerformed(evt);
            }
        });

        CancelChangePassword.setText("Cancel");
        CancelChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelChangePasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ChangePasswordDialogLayout = new javax.swing.GroupLayout(ChangePasswordDialog.getContentPane());
        ChangePasswordDialog.getContentPane().setLayout(ChangePasswordDialogLayout);
        ChangePasswordDialogLayout.setHorizontalGroup(
            ChangePasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ChangePasswordDialogLayout.createSequentialGroup()
                .addGroup(ChangePasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ChangePasswordDialogLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(ConfirmChangePassword)
                        .addGap(107, 107, 107)
                        .addComponent(CancelChangePassword))
                    .addGroup(ChangePasswordDialogLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(TypeNewPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChangePasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(143, 143, 143))
        );
        ChangePasswordDialogLayout.setVerticalGroup(
            ChangePasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChangePasswordDialogLayout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(ChangePasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TypeNewPasswordLabel)
                    .addComponent(ChangePasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(ChangePasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmChangePassword)
                    .addComponent(CancelChangePassword))
                .addGap(98, 98, 98))
        );

        StudentFeedbackDialog.setMinimumSize(new java.awt.Dimension(400, 300));

        TeacherSelection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));

        ProceedStudent.setText("Proceed");
        ProceedStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProceedStudentActionPerformed(evt);
            }
        });

        jLabel7.setText("Select subject : ");

        javax.swing.GroupLayout StudentFeedbackDialogLayout = new javax.swing.GroupLayout(StudentFeedbackDialog.getContentPane());
        StudentFeedbackDialog.getContentPane().setLayout(StudentFeedbackDialogLayout);
        StudentFeedbackDialogLayout.setHorizontalGroup(
            StudentFeedbackDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentFeedbackDialogLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(StudentFeedbackDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ProceedStudent)
                    .addGroup(StudentFeedbackDialogLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TeacherSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        StudentFeedbackDialogLayout.setVerticalGroup(
            StudentFeedbackDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentFeedbackDialogLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(StudentFeedbackDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TeacherSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addComponent(ProceedStudent)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        Subject.setMinimumSize(new java.awt.Dimension(721, 568));

        SubmitStuFeedback.setText("Submit");
        SubmitStuFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitStuFeedbackActionPerformed(evt);
            }
        });

        q1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "5", "4", "3", "2", "1" }));

        q2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "5", "4", "3", "2", "1" }));

        q3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "5", "4", "3", "2", "1" }));

        q4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "5", "4", "3", "2", "1" }));

        q5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "5", "4", "3", "2", "1" }));

        q6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "5", "4", "3", "2", "1" }));

        q7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "5", "4", "3", "2", "1" }));

        q8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "5", "4", "3", "2", "1" }));

        q9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "5", "4", "3", "2", "1" }));

        q10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "5", "4", "3", "2", "1" }));

        jLabel13.setText("The faculty is enthusiastic about the subject.");

        jLabel14.setText("The faculty encourages creative and/or critical thinking.");

        jLabel15.setText("Evaluation of the Blue books.");

        jLabel16.setText("The faculty is regular and punctual to the classes.");

        jLabel17.setText("The interaction of faculty with students.");

        jLabel18.setText("The faculty’s presentation of the course is clear and well-organized.");

        jLabel19.setText("Completion of syllabus in timely manner.");

        jLabel20.setText("The laboratory experiences contribute to my overall understanding of the subject.");

        jLabel21.setText("The faculty clearly explains or demonstrates laboratory techniques and procedures.");

        jLabel22.setText("The faculty effectively plans and organizes laboratory activities.");

        jPanel5.setBackground(new java.awt.Color(0, 102, 255));

        TeachSub.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TeachSub.setForeground(new java.awt.Color(255, 255, 255));
        TeachSub.setText("jLabel13");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Teacher Name : ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Subject : ");

        TeachName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TeachName.setForeground(new java.awt.Color(255, 255, 255));
        TeachName.setText("jLabel12");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TeachName, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TeachSub))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TeachName, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(TeachSub))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SubjectLayout = new javax.swing.GroupLayout(Subject.getContentPane());
        Subject.getContentPane().setLayout(SubjectLayout);
        SubjectLayout.setHorizontalGroup(
            SubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(SubjectLayout.createSequentialGroup()
                .addGroup(SubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SubjectLayout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(SubmitStuFeedback))
                    .addGroup(SubjectLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(SubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addGap(49, 49, 49)
                        .addGroup(SubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(q9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(q8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(q7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(q5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(q4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(q3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(q2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(q1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(q6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        SubjectLayout.setVerticalGroup(
            SubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubjectLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(SubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(5, 5, 5)
                .addGroup(SubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(11, 11, 11)
                .addGroup(SubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(37, 37, 37)
                .addComponent(SubmitStuFeedback)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        StuFeedbackDone.setMinimumSize(new java.awt.Dimension(200, 100));

        jLabel8.setText("Feedback Submitted!!");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StuFeedbackDoneLayout = new javax.swing.GroupLayout(StuFeedbackDone.getContentPane());
        StuFeedbackDone.getContentPane().setLayout(StuFeedbackDoneLayout);
        StuFeedbackDoneLayout.setHorizontalGroup(
            StuFeedbackDoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StuFeedbackDoneLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(StuFeedbackDoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StuFeedbackDoneLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jButton1))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        StuFeedbackDoneLayout.setVerticalGroup(
            StuFeedbackDoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StuFeedbackDoneLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        StuSubError.setMinimumSize(new java.awt.Dimension(200, 100));

        jLabel9.setText("Error : Please complete the form.");

        FeedbackErrorOKButton.setText("OK");
        FeedbackErrorOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FeedbackErrorOKButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StuSubErrorLayout = new javax.swing.GroupLayout(StuSubError.getContentPane());
        StuSubError.getContentPane().setLayout(StuSubErrorLayout);
        StuSubErrorLayout.setHorizontalGroup(
            StuSubErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StuSubErrorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StuSubErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(StuSubErrorLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(FeedbackErrorOKButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        StuSubErrorLayout.setVerticalGroup(
            StuSubErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StuSubErrorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(FeedbackErrorOKButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        FeedbackDone.setMinimumSize(new java.awt.Dimension(400, 400));

        jLabel12.setText("You have already submitted your feedback.");

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FeedbackDoneLayout = new javax.swing.GroupLayout(FeedbackDone.getContentPane());
        FeedbackDone.getContentPane().setLayout(FeedbackDoneLayout);
        FeedbackDoneLayout.setHorizontalGroup(
            FeedbackDoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FeedbackDoneLayout.createSequentialGroup()
                .addGroup(FeedbackDoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FeedbackDoneLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel12))
                    .addGroup(FeedbackDoneLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jButton2)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        FeedbackDoneLayout.setVerticalGroup(
            FeedbackDoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FeedbackDoneLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("USN :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Password :");

        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });

        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        Exitbutton.setText("Exit");
        Exitbutton.setMaximumSize(new java.awt.Dimension(57, 23));
        Exitbutton.setMinimumSize(new java.awt.Dimension(57, 23));
        Exitbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitbuttonMouseClicked(evt);
            }
        });
        Exitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitbuttonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feedback/sandtiger_logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Welcome to BMSCE Feedback System!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(UserField, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                    .addComponent(PasswordField)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(LoginButton)
                                .addGap(18, 18, 18)
                                .addComponent(Exitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginButton)
                    .addComponent(Exitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitbuttonMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitbuttonMouseClicked

    private void ExitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitbuttonActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
        
        try{
         String ud = UserField.getText();   
         CurrentUser = UserField.getText();       
         Class.forName("java.sql.Driver");
         Connection  con = DriverManager.getConnection("jdbc:mysql://localhost/feedback","root","jirs");
            System.out.println("Connecting JDBC...(login)");
            System.out.println("Connection Sucessful!!");
         
        if(UserField.getText().isEmpty() || PasswordField.getText().isEmpty())
            {
                ErrorPane.showMessageDialog(null,"All fields should be filled");//Checking if all fields are filled
            }
        Statement stmt= con.createStatement();
        String q= "select * from student where(USN= "+"'"+UserField.getText()+"');";
        ResultSet rs=stmt.executeQuery(q);
    if(rs.next())
    {
         
         String d_no=rs.getString("USN");
         String d_na=rs.getString("Password");
         String Name=rs.getString("Name");
         //String LastName=rs.getString("last_name");
         currSem=rs.getString("Sem");
         currSec=rs.getString("Sec");
         String pas=new String( PasswordField.getPassword());
         if ((ud.equals(d_no)) && (pas.equals(d_na)))
         {
             PasswordField.setText(null);
             boolean done = rs.getBoolean("Y_N");
             if(done)
             {
                 FeedbackDone.setLocationRelativeTo(null);
                 
                 FeedbackDone.setTitle("Feedback done.");
                 FeedbackDone.setIconImage(new ImageIcon(getClass().getResource("win_logo.png")).getImage());
                 FeedbackDone.setVisible(true);
             }
             /*if(rs.getBoolean("student"))
             {*/
             else
             {
                StudentHome.setIconImage(new ImageIcon(getClass().getResource("win_logo.png")).getImage());
                StudentHome.setSize(642,388);
                StudentHome.setLocationRelativeTo(null);
                
                StudentHome.setVisible(true);
                WelcomeLabel.setText("Welcome, "+Name+/*" "+LastName+*/" !");
                FullName.setText("Name : "+Name/*+" "+LastName*/);
                Section.setText("Section : "+rs.getString("Sec"));
                Sem.setText("Semester : "+rs.getString("Sem"));
                USN.setText("USN : "+rs.getString("USN"));
                Gender.setVisible(false);
                //Gender.setText("Gender : "+rs.getString("gender"));
             //}
             /*else
             {
                TeacherHome.setIconImage(new ImageIcon(getClass().getResource("win_logo.png")).getImage());
                TeacherHome.setSize(200,200);
                TeacherHome.setLocationRelativeTo(null);
                TeacherHome.setVisible(true);
                String Gender = rs.getString("gender");
                String Title = new String();
                if(Gender.equalsIgnoreCase("female"))
                {
                    Title = "Ms.";
                }
                else
                    Title = "Mr.";
                WelcomeLabelTeacher.setText("Welcome "+Title+" "+FirstName+" "+LastName);
                FullNameTeacher.setText("Full Name : "+FirstName+" "+LastName);
                SectionCoveredLabel.setText("Semester and Section covered : "+rs.getString("sem")+" '"+rs.getString("sec")+"'");
             }*/
             }
         }
         else
         if((d_no.equals(ud)) && (!(pas.equals(d_na)))){
             ErrorPane.showMessageDialog(null, "Wrong Password");
         }
         else
             ErrorPane.showMessageDialog(null, "Invalid user name/password.");
       

     stmt.executeQuery(q);
    }
    else
    {
        ErrorPane.showMessageDialog(null, "Wrong username!!");
    }
        }
        catch(Exception e)
        {
            ErrorPane.showMessageDialog(null,"Connectivity Error." );
        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void LogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutButtonActionPerformed
        // TODO add your handling code here:
        StudentHome.setVisible(false);
    }//GEN-LAST:event_LogOutButtonActionPerformed

    private void ChangePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePasswordButtonActionPerformed
        // TODO add your handling code here:
        ChangePasswordDialog.setIconImage(new ImageIcon(getClass().getResource("win_logo.png")).getImage());
          //ChangePasswordDialog.setSize(500,200);
        StudentHome.setVisible(false);
          ChangePasswordDialog.setLocationRelativeTo(null);
          ChangePasswordDialog.setVisible(true);
          
         
        
    }//GEN-LAST:event_ChangePasswordButtonActionPerformed

    private void TeacherLogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeacherLogOutButtonActionPerformed
        // TODO add your handling code here:
        TeacherHome.setVisible(false);
    }//GEN-LAST:event_TeacherLogOutButtonActionPerformed

    private void ChangeUserNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeUserNameButtonActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_ChangeUserNameButtonActionPerformed

    private void DoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneButtonActionPerformed
        // TODO add your handling code here:
        DoneDialog.setVisible(false);
        StudentHome.setVisible(true);
    }//GEN-LAST:event_DoneButtonActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void ConfirmChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmChangePasswordActionPerformed
        // TODO add your handling code here:
        try{
         Class.forName("java.sql.Driver");
         Connection  conn = DriverManager.getConnection("jdbc:mysql://localhost/feedback","root","jirs");
            System.out.println("Connecting JDBC...(Student Password Change)");
            System.out.println("Connection Sucessful!!");
            Statement stmt= conn.createStatement();
            System.out.println("stmt success!!");
          String q ="update student set Password='"+ChangePasswordField.getText()+"'where USN= '"+UserField.getText()+"';";
            System.out.println("q success!!");
          stmt.executeUpdate(q);
            System.out.println("Success!!"); 
            DoneDialog.setLocationRelativeTo(null);
            DoneDialog.setVisible(true);
            ChangePasswordDialog.setVisible(false);       
           
        }
        catch(Exception e){
             ErrorPane.showMessageDialog(null,"Not changed");
             
         }
           
    }//GEN-LAST:event_ConfirmChangePasswordActionPerformed
    
    private void GiveFeedbackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GiveFeedbackButtonActionPerformed
        // TODO add your handling code here:
        //ErrorPane opp = new
        try{
            
         Class.forName("java.sql.Driver");
         Connection  con = DriverManager.getConnection("jdbc:mysql://localhost/feedback","root","jirs");
            System.out.println("Connecting JDBC...(Give Feedback)");
            System.out.println("Connection Sucessful!!");
            Statement stmt= con.createStatement();
            
            String q = "select * from student where(USN= "+"'"+UserField.getText()+"');";
            System.out.println(UserField.getText());
            ResultSet rs = stmt.executeQuery(q);
            if(rs.next())
            {
                String sec=rs.getString("Sec");
                System.out.println(sec);
                String sem=rs.getString("Sem");
                System.out.println(sem);
                String q1 = "select distinct f.subcode from faculty f,student s where ("+sem+"=f.sem1 and '"+sec+"'=f.sec1);";
                ResultSet rs1 = stmt.executeQuery(q1);
                TeacherSelection.removeAllItems();
                
                while (rs1.next()) 
                {
                    String sub = rs1.getString("subcode");
                    TeacherSelection.addItem(sub);                  
                }
                TeacherSelection.addItem(" ");
                StudentFeedbackDialog.setLocationRelativeTo(null);
                StudentHome.setVisible(false);
                StudentFeedbackDialog.setIconImage(new ImageIcon(getClass().getResource("win_logo.png")).getImage());
                StudentFeedbackDialog.setTitle("Select subject");
                StudentFeedbackDialog.setVisible(true);
            }
            
      
        }
        catch(Exception e)
        {
            e.printStackTrace();
            //opp.showMessageDialog(null,"Connectivity Error." );
        }
    }//GEN-LAST:event_GiveFeedbackButtonActionPerformed

    private void CancelChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelChangePasswordActionPerformed
        // TODO add your handling code here:
        ChangePasswordDialog.setVisible(false);
        StudentHome.setVisible(true);
    }//GEN-LAST:event_CancelChangePasswordActionPerformed

    private void ProceedStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProceedStudentActionPerformed
        String sel = (String) TeacherSelection.getSelectedItem();
        currentSubject = (String) TeacherSelection.getSelectedItem();
        try
        {
            Class.forName("java.sql.Driver");
            Connection  con = DriverManager.getConnection("jdbc:mysql://localhost/feedback","root","jirs");
            System.out.println("Connecting JDBC...(feed)");
            System.out.println("Connection Sucessful!!");
            System.out.println(currentSubject);
            Statement stmt = con.createStatement();
            String q = "SELECT * from faculty where subcode='"+currentSubject+"';";
            System.out.println("Query is "+q);
            ResultSet rs = stmt.executeQuery(q);
            System.out.println("rs success!!");
            if(rs.next())
            {
                System.out.println(rs.getString("fname"));
                TeachName.setText(rs.getString("Title")+" "+rs.getString("fname"));
                TeachSub.setText(currentSubject);
                Subject.setTitle("Feedback for "+rs.getString("subcode")+" teacher "+rs.getString("Title")+" "+rs.getString("fname"));
            }
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        Subject.setLocationRelativeTo(null);
        Subject.setIconImage(new ImageIcon(getClass().getResource("win_logo.png")).getImage());
        Subject.setVisible(true);
        
        TeacherSelection.removeItem(sel);
        //Subject.setVisible(true);
        
    }//GEN-LAST:event_ProceedStudentActionPerformed

    private void SubmitStuFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitStuFeedbackActionPerformed
        // TODO add your handling code here:
        if((q1.getSelectedIndex()==0)||(q2.getSelectedIndex()==0)||(q3.getSelectedIndex()==0)||(q4.getSelectedIndex()==0)||(q5.getSelectedIndex()==0)||(q6.getSelectedIndex()==0)||(q7.getSelectedIndex()==0)||(q8.getSelectedIndex()==0)||(q9.getSelectedIndex()==0)||(q10.getSelectedIndex()==0))
        {
            StuSubError.setLocationRelativeTo(null);
            StuSubError.setVisible(true);
        }
        else
        {
            try
            {
                Class.forName("java.sql.Driver");
                Connection  con = DriverManager.getConnection("jdbc:mysql://localhost/feedback","root","jirs");
                System.out.println("Connecting JDBC...(main)");
                System.out.println("Connection Sucessful!!");
                String q = "SELECT sf"+stuSessionNo+" FROM teaches WHERE subcode = '"+currentSubject+"';";
                Statement stmt= con.createStatement();
                ResultSet rs = stmt.executeQuery(q);
                if(rs.next())
                {
                    int tot = rs.getInt(1);
                    System.out.println(tot);
                    int res = Integer.valueOf(q1.getSelectedItem().toString())+Integer.valueOf(q2.getSelectedItem().toString())+Integer.valueOf(q3.getSelectedItem().toString())+Integer.valueOf(q4.getSelectedItem().toString())+Integer.valueOf(q5.getSelectedItem().toString())+Integer.valueOf(q6.getSelectedItem().toString())+Integer.valueOf(q7.getSelectedItem().toString())+Integer.valueOf(q8.getSelectedItem().toString())+Integer.valueOf(q9.getSelectedItem().toString())+Integer.valueOf(q10.getSelectedItem().toString());
                    System.out.println(res);
                    tot+=res;
                    System.out.println(tot);
                    q = "UPDATE teaches SET sf"+stuSessionNo+" = "+tot+" where subcode='"+currentSubject+"';";
                    stmt.executeUpdate(q);
                    StuFeedbackDone.setLocationRelativeTo(null);
                    StuFeedbackDone.setTitle("Done!");
                    StuFeedbackDone.setIconImage(new ImageIcon(getClass().getResource("win_logo.png")).getImage());
                    StuFeedbackDone.setVisible(true);
                }
                
            }   
            catch(Exception e)
            {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_SubmitStuFeedbackActionPerformed

    private void FeedbackErrorOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FeedbackErrorOKButtonActionPerformed
        // TODO add your handling code here:
        StuSubError.setVisible(false);
    }//GEN-LAST:event_FeedbackErrorOKButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        StuFeedbackDone.setVisible(false);
        Subject.setVisible(false);
        q1.setSelectedIndex(0);
        q2.setSelectedIndex(0);
        q3.setSelectedIndex(0);
        q4.setSelectedIndex(0);
        q5.setSelectedIndex(0);
        q6.setSelectedIndex(0);
        q7.setSelectedIndex(0);
        q8.setSelectedIndex(0);
        q9.setSelectedIndex(0);
        q10.setSelectedIndex(0);
        if(TeacherSelection.getSelectedItem().toString().equalsIgnoreCase(" "))
        {
            StudentFeedbackDialog.setVisible(false);
            GiveFeedbackButton.setVisible(false);
            LogOutButton.setVisible(true);
            StudentHome.setVisible(true);
            try
            {
                Class.forName("java.sql.Driver");
                Connection  con = DriverManager.getConnection("jdbc:mysql://localhost/feedback","root","jirs");
                System.out.println("Connecting JDBC...(main)");
                System.out.println("Connection Sucessful!!");
                Statement stmt= con.createStatement();
                String q = "UPDATE student set `Y_N`=1 WHERE `USN`='"+CurrentUser+"';";
                stmt.executeUpdate(q);
            }
            catch(Exception e)
            {
                e.printStackTrace();;
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        FeedbackDone.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    private String CurrentUser;
    private String currentSubject;
    private String currSem;
    private String currSec;
    public int stuSessionNo=1;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelChangePassword;
    private javax.swing.JButton ChangePasswordButton;
    private javax.swing.JDialog ChangePasswordDialog;
    private javax.swing.JPasswordField ChangePasswordField;
    private javax.swing.JButton ChangeUserNameButton;
    private javax.swing.JButton ConfirmChangePassword;
    private javax.swing.JButton DoneButton;
    private javax.swing.JDialog DoneDialog;
    private javax.swing.JOptionPane ErrorPane;
    private javax.swing.JButton Exitbutton;
    private javax.swing.JDialog FeedbackDone;
    private javax.swing.JButton FeedbackErrorOKButton;
    private javax.swing.JLabel FullName;
    private javax.swing.JLabel FullNameTeacher;
    private javax.swing.JLabel Gender;
    private javax.swing.JButton GiveFeedbackButton;
    private javax.swing.JButton LogOutButton;
    private javax.swing.JButton LoginButton;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JButton ProceedStudent;
    private javax.swing.JLabel Section;
    private javax.swing.JLabel SectionCoveredLabel;
    private javax.swing.JLabel Sem;
    private javax.swing.JDialog StuFeedbackDone;
    private javax.swing.JDialog StuSubError;
    private javax.swing.JDialog StudentFeedbackDialog;
    private javax.swing.JDialog StudentHome;
    private javax.swing.JDialog Subject;
    private javax.swing.JButton SubmitStuFeedback;
    private javax.swing.JLabel TeachName;
    private javax.swing.JLabel TeachSub;
    private javax.swing.JButton TeacherChangePasswordButton;
    private javax.swing.JButton TeacherGiveFeedback;
    private javax.swing.JDialog TeacherHome;
    private javax.swing.JButton TeacherLogOutButton;
    private javax.swing.JComboBox TeacherSelection;
    private javax.swing.JLabel TypeNewPasswordLabel;
    private javax.swing.JLabel USN;
    private javax.swing.JTextField UserField;
    private javax.swing.JLabel WelcomeLabel;
    private javax.swing.JLabel WelcomeLabelTeacher;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JComboBox q1;
    private javax.swing.JComboBox q10;
    private javax.swing.JComboBox q2;
    private javax.swing.JComboBox q3;
    private javax.swing.JComboBox q4;
    private javax.swing.JComboBox q5;
    private javax.swing.JComboBox q6;
    private javax.swing.JComboBox q7;
    private javax.swing.JComboBox q8;
    private javax.swing.JComboBox q9;
    // End of variables declaration//GEN-END:variables
}
