/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package feedback;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;

/**
 *
 * @author owner
 */
public class TLogin extends javax.swing.JFrame {

    /**
     * Creates new form TLogin
     */
    public TLogin() {
        initComponents();
        this.setTitle("BMSCE Feedback System");
        this.setIconImage(new ImageIcon(getClass().getResource("win_logo.png")).getImage());
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginErrorPane = new javax.swing.JOptionPane();
        TeacherHome = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        WelcomeLabel = new javax.swing.JLabel();
        FullNameTeacher = new javax.swing.JLabel();
        SectionCoveredLabel = new javax.swing.JLabel();
        GiveFeedbackButton = new javax.swing.JButton();
        ChangePasswordButton = new javax.swing.JButton();
        LogOutButton = new javax.swing.JButton();
        SubjectLabel = new javax.swing.JLabel();
        GiveFeedBack = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        TeacherList = new javax.swing.JComboBox();
        ProceedButton = new javax.swing.JButton();
        PeerWindow = new javax.swing.JDialog();
        q5 = new javax.swing.JComboBox();
        q6 = new javax.swing.JComboBox();
        q4 = new javax.swing.JComboBox();
        q9 = new javax.swing.JComboBox();
        q10 = new javax.swing.JComboBox();
        q7 = new javax.swing.JComboBox();
        q8 = new javax.swing.JComboBox();
        q1 = new javax.swing.JComboBox();
        q2 = new javax.swing.JComboBox();
        q3 = new javax.swing.JComboBox();
        SubmitButton = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        FeedTeacherLabel = new javax.swing.JLabel();
        FeedTeacherClass = new javax.swing.JLabel();
        FillFormError = new javax.swing.JDialog();
        FillFormErrorOK = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        FeedbackDone = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        FeedbackDoneOKButton = new javax.swing.JButton();
        ChangePasswordDialog = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        ChangePasswordProceed = new javax.swing.JButton();
        CancelChangePassword = new javax.swing.JButton();
        ChangePasswordField = new javax.swing.JPasswordField();
        ChangePasswordDone = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        ChangePasswordDoneOKButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        FacultyNoField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        TeacherHome.setMinimumSize(new java.awt.Dimension(700, 500));

        jPanel3.setBackground(new java.awt.Color(0, 102, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        WelcomeLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        WelcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        WelcomeLabel.setText("Welcome");
        WelcomeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        WelcomeLabel.setMaximumSize(new java.awt.Dimension(0, 0));
        WelcomeLabel.setMinimumSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(WelcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(WelcomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
        );

        FullNameTeacher.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FullNameTeacher.setText("Name");

        SectionCoveredLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SectionCoveredLabel.setText("Section Covered");

        GiveFeedbackButton.setText("Give Feedback");
        GiveFeedbackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GiveFeedbackButtonActionPerformed(evt);
            }
        });

        ChangePasswordButton.setText("Change Password");
        ChangePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePasswordButtonActionPerformed(evt);
            }
        });

        LogOutButton.setText("Logout");
        LogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutButtonActionPerformed(evt);
            }
        });

        SubjectLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SubjectLabel.setText("jLabel5");

        javax.swing.GroupLayout TeacherHomeLayout = new javax.swing.GroupLayout(TeacherHome.getContentPane());
        TeacherHome.getContentPane().setLayout(TeacherHomeLayout);
        TeacherHomeLayout.setHorizontalGroup(
            TeacherHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeacherHomeLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(523, 523, 523))
            .addGroup(TeacherHomeLayout.createSequentialGroup()
                .addGroup(TeacherHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TeacherHomeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(TeacherHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FullNameTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SectionCoveredLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(TeacherHomeLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(GiveFeedbackButton)
                        .addGap(81, 81, 81)
                        .addComponent(ChangePasswordButton)
                        .addGap(92, 92, 92)
                        .addComponent(LogOutButton))
                    .addGroup(TeacherHomeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SubjectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TeacherHomeLayout.setVerticalGroup(
            TeacherHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeacherHomeLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(FullNameTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SectionCoveredLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SubjectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(TeacherHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GiveFeedbackButton)
                    .addComponent(ChangePasswordButton)
                    .addComponent(LogOutButton))
                .addGap(30, 30, 30))
        );

        GiveFeedBack.setMinimumSize(new java.awt.Dimension(397, 359));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Select peer : ");

        ProceedButton.setText("Proceed");
        ProceedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProceedButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GiveFeedBackLayout = new javax.swing.GroupLayout(GiveFeedBack.getContentPane());
        GiveFeedBack.getContentPane().setLayout(GiveFeedBackLayout);
        GiveFeedBackLayout.setHorizontalGroup(
            GiveFeedBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GiveFeedBackLayout.createSequentialGroup()
                .addGroup(GiveFeedBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GiveFeedBackLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(TeacherList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GiveFeedBackLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(ProceedButton)))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        GiveFeedBackLayout.setVerticalGroup(
            GiveFeedBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GiveFeedBackLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(GiveFeedBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TeacherList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(ProceedButton)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        PeerWindow.setMinimumSize(new java.awt.Dimension(602, 620));

        q5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "5", "4", "3", "2", "1" }));

        q6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "5", "4", "3", "2", "1" }));

        q4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "5", "4", "3", "2", "1" }));

        q9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "5", "4", "3", "2", "1" }));

        q10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "5", "4", "3", "2", "1" }));

        q7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "5", "4", "3", "2", "1" }));

        q8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "5", "4", "3", "2", "1" }));

        q1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "5", "4", "3", "2", "1" }));

        q2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "5", "4", "3", "2", "1" }));

        q3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "5", "4", "3", "2", "1" }));

        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        jLabel17.setText("The interaction of faculty with students.");

        jLabel16.setText("Teacher's control over the class");

        jLabel18.setText("The faculty’s presentation of the course is clear and well-organized.");

        jLabel19.setText("Keeps the student focussed on objectives.");

        jLabel20.setText("The faculty uses class time effectively.");

        jLabel21.setText("The faculty clearly explains or demonstrates laboratory techniques and procedures.");

        jLabel22.setText("The faculty effectively plans and organizes laboratory activities.");

        jLabel15.setText("Class Decorum");

        jLabel14.setText("The faculty encourages creative and/or critical thinking.");

        jLabel13.setText("The faculty is enthusiastic about the subject.");

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));

        FeedTeacherLabel.setForeground(new java.awt.Color(255, 255, 255));
        FeedTeacherLabel.setText("Teacher Name");

        FeedTeacherClass.setForeground(new java.awt.Color(255, 255, 255));
        FeedTeacherClass.setText("Class Handled");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FeedTeacherLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FeedTeacherClass, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FeedTeacherLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FeedTeacherClass, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout PeerWindowLayout = new javax.swing.GroupLayout(PeerWindow.getContentPane());
        PeerWindow.getContentPane().setLayout(PeerWindowLayout);
        PeerWindowLayout.setHorizontalGroup(
            PeerWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PeerWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PeerWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(PeerWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(q4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
            .addGroup(PeerWindowLayout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(SubmitButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PeerWindowLayout.setVerticalGroup(
            PeerWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PeerWindowLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PeerWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PeerWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PeerWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PeerWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PeerWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PeerWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PeerWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PeerWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PeerWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PeerWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(q10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(SubmitButton)
                .addGap(36, 36, 36))
        );

        FillFormError.setMinimumSize(new java.awt.Dimension(412, 348));

        FillFormErrorOK.setText("OK");
        FillFormErrorOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FillFormErrorOKActionPerformed(evt);
            }
        });

        jLabel7.setText("Error : Please complete the form.");

        javax.swing.GroupLayout FillFormErrorLayout = new javax.swing.GroupLayout(FillFormError.getContentPane());
        FillFormError.getContentPane().setLayout(FillFormErrorLayout);
        FillFormErrorLayout.setHorizontalGroup(
            FillFormErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FillFormErrorLayout.createSequentialGroup()
                .addGroup(FillFormErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FillFormErrorLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(FillFormErrorOK))
                    .addGroup(FillFormErrorLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel7)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        FillFormErrorLayout.setVerticalGroup(
            FillFormErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FillFormErrorLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FillFormErrorOK)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        FeedbackDone.setMinimumSize(new java.awt.Dimension(306, 298));

        jLabel8.setText("Done!");

        FeedbackDoneOKButton.setText("OK");
        FeedbackDoneOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FeedbackDoneOKButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FeedbackDoneLayout = new javax.swing.GroupLayout(FeedbackDone.getContentPane());
        FeedbackDone.getContentPane().setLayout(FeedbackDoneLayout);
        FeedbackDoneLayout.setHorizontalGroup(
            FeedbackDoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FeedbackDoneLayout.createSequentialGroup()
                .addGroup(FeedbackDoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FeedbackDoneLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel8))
                    .addGroup(FeedbackDoneLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(FeedbackDoneOKButton)))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        FeedbackDoneLayout.setVerticalGroup(
            FeedbackDoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FeedbackDoneLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FeedbackDoneOKButton)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        ChangePasswordDialog.setMinimumSize(new java.awt.Dimension(475, 354));

        jLabel9.setText("Type new password : ");

        ChangePasswordProceed.setText("Submit");
        ChangePasswordProceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePasswordProceedActionPerformed(evt);
            }
        });

        CancelChangePassword.setText("Cancel");
        CancelChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelChangePasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ChangePasswordDialogLayout = new javax.swing.GroupLayout(ChangePasswordDialog.getContentPane());
        ChangePasswordDialog.getContentPane().setLayout(ChangePasswordDialogLayout);
        ChangePasswordDialogLayout.setHorizontalGroup(
            ChangePasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChangePasswordDialogLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(ChangePasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ChangePasswordProceed)
                    .addComponent(jLabel9))
                .addGroup(ChangePasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ChangePasswordDialogLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(CancelChangePassword))
                    .addGroup(ChangePasswordDialogLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ChangePasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        ChangePasswordDialogLayout.setVerticalGroup(
            ChangePasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChangePasswordDialogLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(ChangePasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ChangePasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(ChangePasswordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChangePasswordProceed)
                    .addComponent(CancelChangePassword))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        ChangePasswordDone.setMinimumSize(new java.awt.Dimension(439, 354));

        jLabel10.setText("Password Changed!");

        ChangePasswordDoneOKButton.setText("OK");
        ChangePasswordDoneOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePasswordDoneOKButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ChangePasswordDoneLayout = new javax.swing.GroupLayout(ChangePasswordDone.getContentPane());
        ChangePasswordDone.getContentPane().setLayout(ChangePasswordDoneLayout);
        ChangePasswordDoneLayout.setHorizontalGroup(
            ChangePasswordDoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChangePasswordDoneLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jLabel10)
                .addContainerGap(146, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ChangePasswordDoneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ChangePasswordDoneOKButton)
                .addGap(172, 172, 172))
        );
        ChangePasswordDoneLayout.setVerticalGroup(
            ChangePasswordDoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChangePasswordDoneLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(ChangePasswordDoneOKButton)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feedback/sandtiger_logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Welcome to BMSCE Feedback System!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Faculty No. : ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Password : ");

        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });

        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LoginButton)
                                .addGap(18, 18, 18)
                                .addComponent(ExitButton))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(FacultyNoField)
                                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(FacultyNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginButton)
                    .addComponent(ExitButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("java.sql.Driver");
            Connection  con = DriverManager.getConnection("jdbc:mysql://localhost/feedback","root","jirs");
            System.out.println("Connecting JDBC...(main)");
            System.out.println("Connection Sucessful!!");
            if(FacultyNoField.getText().isEmpty()||PasswordField.getText().isEmpty())
            {
                LoginErrorPane.showMessageDialog(null, "All fields should be filled.");                
            }
            currentUser = FacultyNoField.getText();
            Statement stmt = con.createStatement();
            String q = "SELECT * FROM faculty where fno="+currentUser+";";
            ResultSet rs = stmt.executeQuery(q);
            if(rs.next())
            {
                String pass = rs.getString("password");
                p1 = rs.getString("peer1");
                p2 = rs.getString("peer2");
                if(!(PasswordField.getText().equals(pass)))
                {
                    LoginErrorPane.showMessageDialog(null, "Wrong password.");
                }
                else
                {
                    //PasswordField
                    WelcomeLabel.setText("Welcome "+rs.getString("Title")+" "+rs.getString("fname"));
                    FullNameTeacher.setText("Name : "+rs.getString("Title")+" "+rs.getString("fname"));
                    SectionCoveredLabel.setText("Class and Section Handled : "+rs.getString("sem1")+" "+rs.getString("sec1"));
                    SubjectLabel.setText("Subject Taught : "+rs.getString("subcode"));
                    TeacherHome.setLocationRelativeTo(null);
                    TeacherHome.setTitle("Welcome "+rs.getString("Title")+" "+rs.getString("fname"));
                    TeacherHome.setIconImage(new ImageIcon(getClass().getResource("win_logo.png")).getImage());
                    TeacherHome.setVisible(true);
                }
            }
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void ChangePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePasswordButtonActionPerformed
        // TODO add your handling code here:
        ChangePasswordDialog.setVisible(true);
    }//GEN-LAST:event_ChangePasswordButtonActionPerformed

    private void GiveFeedbackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GiveFeedbackButtonActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("java.sql.Driver");
            Connection  con = DriverManager.getConnection("jdbc:mysql://localhost/feedback","root","jirs");
            System.out.println("Connecting JDBC...(main)");
            System.out.println("Connection Sucessful!!");
            String q = "select fname from faculty where fno="+p1+" or fno="+p2;
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(q);
            TeacherList.removeAllItems();
            while(rs.next())
            {
                String peer = rs.getString("fname");
                TeacherList.addItem(peer);
            }
            TeacherList.addItem(" ");
            GiveFeedBack.setLocationRelativeTo(null);
            GiveFeedBack.setIconImage(new ImageIcon(getClass().getResource("win_logo.png")).getImage());
            GiveFeedBack.setTitle("Select peer :");
            GiveFeedBack.setVisible(true);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_GiveFeedbackButtonActionPerformed

    private void ProceedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProceedButtonActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("java.sql.Driver");
            Connection  con = DriverManager.getConnection("jdbc:mysql://localhost/feedback","root","jirs");
            System.out.println("Connecting JDBC...(main)");
            System.out.println("Connection Sucessful!!");
            p1Name = (String) TeacherList.getSelectedItem();
            Statement stmt = con.createStatement();
            String q ="select * from faculty where fname ='"+p1Name+"';";
            ResultSet rs = stmt.executeQuery(q);
            if(rs.next())
            {
                FeedTeacherLabel.setText("Faculty name : "+rs.getString("Title")+" "+rs.getString("fname"));
                FeedTeacherClass.setText("Class handled : "+rs.getString("sem1")+" "+rs.getString("sec1"));
            }
            PeerWindow.setLocationRelativeTo(null);
            PeerWindow.setIconImage(new ImageIcon(getClass().getResource("win_logo.png")).getImage());
            PeerWindow.setTitle("Feedback for "+rs.getString("Title")+" "+rs.getString("fname"));
            PeerWindow.setVisible(true);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }

    }//GEN-LAST:event_ProceedButtonActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // TODO add your handling code here:
        if((q1.getSelectedIndex()==0)||(q2.getSelectedIndex()==0)||(q3.getSelectedIndex()==0)||(q4.getSelectedIndex()==0)||(q5.getSelectedIndex()==0)||(q6.getSelectedIndex()==0)||(q7.getSelectedIndex()==0)||(q8.getSelectedIndex()==0)||(q9.getSelectedIndex()==0)||(q10.getSelectedIndex()==0))
        {
            FillFormError.setLocationRelativeTo(null);
            FillFormError.setIconImage(new ImageIcon(getClass().getResource("win_logo.png")).getImage());
            FillFormError.setTitle("Error!");
            FillFormError.setVisible(true);
        }
        else
        {
            try
            {
                Class.forName("java.sql.Driver");
                Connection  con = DriverManager.getConnection("jdbc:mysql://localhost/feedback","root","jirs");
                System.out.println("Connecting JDBC...(main)");
                System.out.println("Connection Sucessful!!");
                Statement stmt = con.createStatement();
                String q ="select pf1 from teaches where fno='"+p1+"';";
                ResultSet rs = stmt.executeQuery(q);
                if(rs.next())
                {
                    tot =rs.getInt(1);
                    int res = Integer.valueOf(q1.getSelectedItem().toString())+Integer.valueOf(q2.getSelectedItem().toString())+Integer.valueOf(q3.getSelectedItem().toString())+Integer.valueOf(q4.getSelectedItem().toString())+Integer.valueOf(q5.getSelectedItem().toString())+Integer.valueOf(q6.getSelectedItem().toString())+Integer.valueOf(q7.getSelectedItem().toString())+Integer.valueOf(q8.getSelectedItem().toString())+Integer.valueOf(q9.getSelectedItem().toString())+Integer.valueOf(q10.getSelectedItem().toString());
                    tot+=res;    
                    q = "update teaches set pf1="+tot+" where fno="+p1+";";
                    stmt.executeUpdate(q);
                    FeedbackDone.setLocationRelativeTo(null);
                    FeedbackDone.setIconImage(new ImageIcon(getClass().getResource("win_logo.png")).getImage());
                    FeedbackDone.setTitle("Done!");
                    FeedbackDone.setVisible(true);
                }
            }
            catch(Exception e)
            {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void FillFormErrorOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FillFormErrorOKActionPerformed
        // TODO add your handling code here:
        FillFormError.setVisible(false);
    }//GEN-LAST:event_FillFormErrorOKActionPerformed

    private void FeedbackDoneOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FeedbackDoneOKButtonActionPerformed
        // TODO add your handling code here:
        FeedbackDone.setVisible(false);
    }//GEN-LAST:event_FeedbackDoneOKButtonActionPerformed

    private void LogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutButtonActionPerformed
        // TODO add your handling code here:
        TeacherHome.setVisible(false);
    }//GEN-LAST:event_LogOutButtonActionPerformed

    private void CancelChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelChangePasswordActionPerformed
        // TODO add your handling code here:
        ChangePasswordDialog.setVisible(false);
    }//GEN-LAST:event_CancelChangePasswordActionPerformed

    private void ChangePasswordProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePasswordProceedActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("java.sql.Driver");
            Connection  con = DriverManager.getConnection("jdbc:mysql://localhost/feedback","root","jirs");
            System.out.println("Connecting JDBC...(main)");
            System.out.println("Connection Sucessful!!");
            Statement stmt = con.createStatement();
            String q = "UPDATE faculty SET password = '"+ChangePasswordField.getText()+"' WHERE fno="+currentUser+";";
            stmt.executeUpdate(q);
            ChangePasswordDone.setVisible(true);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }

    }//GEN-LAST:event_ChangePasswordProceedActionPerformed

    private void ChangePasswordDoneOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePasswordDoneOKButtonActionPerformed
        // TODO add your handling code here:
        ChangePasswordDone.setVisible(false);
        ChangePasswordDialog.setVisible(false);
    }//GEN-LAST:event_ChangePasswordDoneOKButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TLogin().setVisible(true);
            }
        });
    }
    private String currentUser;
    private String p1;
    private String p2;
    private String p1Name;
    private String p2Name;
    private int tot;
    private int res;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelChangePassword;
    private javax.swing.JButton ChangePasswordButton;
    private javax.swing.JDialog ChangePasswordDialog;
    private javax.swing.JDialog ChangePasswordDone;
    private javax.swing.JButton ChangePasswordDoneOKButton;
    private javax.swing.JPasswordField ChangePasswordField;
    private javax.swing.JButton ChangePasswordProceed;
    private javax.swing.JButton ExitButton;
    private javax.swing.JTextField FacultyNoField;
    private javax.swing.JLabel FeedTeacherClass;
    private javax.swing.JLabel FeedTeacherLabel;
    private javax.swing.JDialog FeedbackDone;
    private javax.swing.JButton FeedbackDoneOKButton;
    private javax.swing.JDialog FillFormError;
    private javax.swing.JButton FillFormErrorOK;
    private javax.swing.JLabel FullNameTeacher;
    private javax.swing.JDialog GiveFeedBack;
    private javax.swing.JButton GiveFeedbackButton;
    private javax.swing.JButton LogOutButton;
    private javax.swing.JButton LoginButton;
    private javax.swing.JOptionPane LoginErrorPane;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JDialog PeerWindow;
    private javax.swing.JButton ProceedButton;
    private javax.swing.JLabel SectionCoveredLabel;
    private javax.swing.JLabel SubjectLabel;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JDialog TeacherHome;
    private javax.swing.JComboBox TeacherList;
    private javax.swing.JLabel WelcomeLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox q1;
    private javax.swing.JComboBox q10;
    private javax.swing.JComboBox q2;
    private javax.swing.JComboBox q3;
    private javax.swing.JComboBox q4;
    private javax.swing.JComboBox q5;
    private javax.swing.JComboBox q6;
    private javax.swing.JComboBox q7;
    private javax.swing.JComboBox q8;
    private javax.swing.JComboBox q9;
    // End of variables declaration//GEN-END:variables
}
